name: Build and run Spring Boot App

on:
  push:
    branches: [ "main" ] # Or your main branch name
  pull_request:
    branches: [ "main" ] # Or your main branch name

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run Docker image
        run: |
          docker build . --file Dockerfile
          docker compose up