name: Build and run Spring Boot App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run Docker image
        run: |
          docker build . --file Dockerfile
          docker compose up -d  # Run in detached mode

      - name: Stop and remove containers
        run: docker compose down
