name: Build and run Spring Boot App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run Docker container
        run: |
          docker build . --file Dockerfile
          docker compose up -d  # Start container in detached mode

      - name: Print running containers
        run: docker ps
      - name: Keep workflow active for debugging (Optional)
        run: sleep 10

